name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          cd lab7
          g++ -std=c++11 -lm -ftest-coverage -fprofile-arcs -O0 -o test main_test.cpp tourist.cpp
          echo "1 2 3 0" > in.txt
          ./test < in.txt
          gcov -abcfu tourist.cpp 
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: |
              ./lab7/tourist.cpp.gcov
